Starting 24.0.0-beta.0 development (#1603)

diff --git a/.github/workflows/push-pull.yml b/.github/workflows/push-pull.yml
--- a/.github/workflows/push-pull.yml
+++ b/.github/workflows/push-pull.yml
@@ -2,11 +2,11 @@ name: HyperHDR CI Build
 
 on:
   push:
+  pull_request:  
 
 env:
-    USE_CACHE: ${{ vars.USE_CACHE && vars.USE_CACHE || true }}
-    RESET_CACHE: ${{ vars.RESET_CACHE && vars.RESET_CACHE || false }}
-    USE_CODEQL: ${{ vars.USE_CODEQL && vars.USE_CODEQL || false }}
+    USE_CACHE: ${{ fromJSON(vars.USE_CACHE || 'false') }}
+    RESET_CACHE: ${{ fromJSON(vars.RESET_CACHE || 'false') }}
     BUILD_ARCHIVES: ${{ startsWith(github.event.ref, 'refs/tags') && true || false }}
 
 jobs:
@@ -18,12 +18,13 @@ jobs:
   Linux:
     name: ${{ matrix.architecture }}/${{ matrix.distroName}}:${{ matrix.distroVersion }}
     runs-on: ${{ startsWith(matrix.architecture, 'arm') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
+    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
     env:
       platform: ${{ startsWith(matrix.architecture, 'arm') && 'rpi' || 'linux' }}
     strategy:      
       matrix:
         distroName: [debian]
-        distroVersion: [bullseye, bookworm, trixie]
+        distroVersion: [bullseye, bookworm, trixie, forky]
         architecture: [amd64, armhf, arm64]        
         include:
           - distroName: ubuntu
@@ -84,15 +85,19 @@ jobs:
           name: release-artifact-${{ matrix.architecture }}-${{ matrix.distroName }}-${{ matrix.distroVersion }}
           path: deploy/Hyper*
 
+      - name: Find artifact file
+        id: find_artifact
+        if: startsWith(github.event.ref, 'refs/tags') == false
+        run: |
+          ARTIFACT_FILE=$(find deploy -maxdepth 1 -type f \( -name "Hyper*.deb" -o -name "Hyper*.zst" -o -name "Hyper*.rpm" \) | head -n 1)
+          echo "installer_artifact_path=$ARTIFACT_FILE" >> $GITHUB_OUTPUT
+
       - name: Upload artifacts from commit
-        if: startsWith(github.event.ref, 'refs/tags') == false && github.event_name != 'pull_request'
+        if: startsWith(github.event.ref, 'refs/tags') == false && steps.find_artifact.outputs.installer_artifact_path != ''
         uses: actions/upload-artifact@v7.0.1
         with:
-          name: Linux-${{ matrix.architecture }}-${{ matrix.distroName }}-${{ matrix.distroVersion }}-installer
-          path: |
-            deploy/Hyper*.deb
-            deploy/Hyper*.zst
-            deploy/Hyper*.rpm
+          path: ${{ steps.find_artifact.outputs.installer_artifact_path }}
+          archive: false
 
 ######################
 ######## macOS #######
@@ -101,6 +106,7 @@ jobs:
   macOS:
     name: ${{ matrix.JOB_NAME }}
     runs-on: ${{ matrix.JOB_RUNNER }}
+    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
     strategy:
       matrix:
         include:        
@@ -152,12 +158,19 @@ jobs:
             name: release-artifact-${{ matrix.JOB_RUNNER }}      
             path: build/Hyper*.dmg
 
+      - name: Find artifact file
+        id: find_artifact
+        if: startsWith(github.event.ref, 'refs/tags') == false
+        run: |
+          ARTIFACT_FILE=$(ls -S build/Hyper*.dmg 2>/dev/null | head -n 1)
+          echo "installer_artifact_path=$ARTIFACT_FILE" >> $GITHUB_OUTPUT
+
       - name: Upload artifacts from commit
-        if: startsWith(github.event.ref, 'refs/tags') == false && github.event_name != 'pull_request'
+        if: startsWith(github.event.ref, 'refs/tags') == false && steps.find_artifact.outputs.installer_artifact_path != ''
         uses: actions/upload-artifact@v7.0.1
         with:
-            name: Apple_macOS_${{ matrix.NICE_NAME }}_DMG_installer
-            path: build/Hyper*.dmg
+            path: ${{ steps.find_artifact.outputs.installer_artifact_path }}
+            archive: false
 
 ######################
 ###### Windows #######
@@ -166,6 +179,7 @@ jobs:
   windows:
     name: Windows
     runs-on: ${{ matrix.os }}
+    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
     strategy:
       matrix:
         os: [windows-2022]
@@ -201,7 +215,7 @@ jobs:
           Invoke-WebRequest -UserAgent "Wget" -Uri "https://prdownloads.sourceforge.net/nsis/nsis-3.11-setup.exe" -OutFile nsis.exe
           Start-Process -Wait nsis.exe -ArgumentList "/S","/D=$env:TOOLKIT_DIR\nsis"
           New-Item -ItemType Directory -Force -Path "$env:TOOLKIT_DIR\ccache" | Out-Null
-          Invoke-WebRequest -Method Get -Uri https://github.com/ccache/ccache/releases/download/v4.12/ccache-4.12-windows-x86_64.zip -OutFile "$env:TOOLKIT_DIR\ccache\ccache.zip" -UseBasicParsing
+          Invoke-WebRequest -Method Get -Uri https://github.com/ccache/ccache/releases/download/v4.14/ccache-4.14-windows-x86_64.zip -OutFile "$env:TOOLKIT_DIR\ccache\ccache.zip" -UseBasicParsing
           pip install aqtinstall
           aqt install-qt -O "$env:TOOLKIT_DIR\Qt" windows desktop $env:QT_VERSION "win64_msvc${env:MSVC}_64" -m qtserialport
 
@@ -238,11 +252,27 @@ jobs:
           GH_TOKEN: ${{ github.token }}
 
       - name: Upload unsigned artifacts
+        if:  github.event_name != 'pull_request' && fromJSON(vars.USE_SIGNPATH || 'false')
         uses: actions/upload-artifact@v7.0.1
         with:
           name: unsigned-windows-installer
-          path: build/Hyper*
+          path: build/Hyper*.exe
           retention-days: 1
+
+      - name: Find artifact file
+        id: find_artifact
+        if: startsWith(github.event.ref, 'refs/tags') == false && fromJSON(vars.USE_SIGNPATH || 'false') == false
+        shell: bash
+        run: |
+          ARTIFACT_FILE=$(ls -S build/Hyper*.exe 2>/dev/null | head -n 1)
+          echo "installer_artifact_path=$ARTIFACT_FILE" >> $GITHUB_OUTPUT
+
+      - name: Upload artifacts from commit
+        if: startsWith(github.event.ref, 'refs/tags') == false && steps.find_artifact.outputs.installer_artifact_path != ''
+        uses: actions/upload-artifact@v7.0.1
+        with:
+            path: ${{ steps.find_artifact.outputs.installer_artifact_path }}
+            archive: false          
 
 ################################
 ###### Sign Windows ############
@@ -252,8 +282,7 @@ jobs:
     name: Sign Windows Installer
     needs: [windows]
     runs-on: ubuntu-24.04
-    env:
-      USE_SIGNPATH: ${{ vars.USE_SIGNPATH || 'false' }}
+    if:  github.event_name != 'pull_request' && fromJSON(vars.USE_SIGNPATH || 'false')
     steps:
       - name: Download unsigned artifact
         uses: actions/download-artifact@v8.0.1
@@ -262,18 +291,16 @@ jobs:
           path: to_sign
 
       - name: Check SignPath Secrets
-        if: env.USE_SIGNPATH == 'true' && github.event_name != 'pull_request'
         env:
           SIGNPATH_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
           SIGNPATH_ORGANIZATION_ID: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
         run: |
           if [ -z "$SIGNPATH_TOKEN" ] || [ -z "$SIGNPATH_ORGANIZATION_ID" ]; then
-            echo "USE_SIGNPATH=false" >> $GITHUB_ENV
-            echo "SignPath secrets not found. Skipping signing process."
+            echo "SignPath secrets not found."
+            exit 1
           fi
 
       - name: Upload unsigned ZIP to GitHub (SignPath V2 requirement)
-        if: ${{ env.USE_SIGNPATH == 'true' }}
         id: upload-unsigned-artifact
         uses: actions/upload-artifact@v7.0.1
         with:
@@ -282,7 +309,6 @@ jobs:
           retention-days: 1
 
       - name: Sign artifact with SignPath
-        if: env.USE_SIGNPATH == 'true'
         id: signpath_step
         uses: signpath/github-action-submit-signing-request@v2
         with:
@@ -295,7 +321,7 @@ jobs:
           output-artifact-directory: signed_artifact
 
       - name: Check SignPath result & fail if needed
-        if: always() && env.USE_SIGNPATH == 'true'
+        if: always()
         run: |
           if [ "${{ steps.signpath_step.outcome }}" != "success" ]; then
             echo "::error::SignPath action failed technically (check logs for timeout/network issues)."
@@ -310,18 +336,18 @@ jobs:
           echo "Signing successful. Artifacts found in 'signed_artifact'."
           
       - name: Upload artifacts (release)
-        if: startsWith(github.event.ref, 'refs/tags') && github.event_name != 'pull_request'
+        if: startsWith(github.event.ref, 'refs/tags')
         uses: actions/upload-artifact@v7.0.1
         with:
           name: release-artifact-windows
-          path: ${{ env.USE_SIGNPATH == 'true' && 'signed_artifact' || 'to_sign' }}/Hyper*.exe
+          path: signed_artifact/Hyper*.exe
           
       - name: Upload artifacts from commit
-        if: startsWith(github.event.ref, 'refs/tags') == false && github.event_name != 'pull_request'
+        if: startsWith(github.event.ref, 'refs/tags') == false
         uses: actions/upload-artifact@v7.0.1
         with:
-          name: Windows_x64_setup_${{ env.USE_SIGNPATH == 'true' && 'signed' || 'unsigned' }}
-          path: ${{ env.USE_SIGNPATH == 'true' && 'signed_artifact' || 'to_sign' }}/Hyper*.exe
+          name: Windows_x64_setup_signed
+          path: signed_artifact/Hyper*.exe
 
 ################################
 ####### CodeQL support #########
@@ -330,7 +356,7 @@ jobs:
   analyze:
     name: Analyze (CodeQL)
     runs-on: ubuntu-latest
-    if: ${{ vars.USE_CODEQL == 'true' && vars.USE_CODEQL || false }}
+    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && fromJSON(vars.USE_CODEQL || 'false')    
 
     permissions:
       actions: read
@@ -345,13 +371,11 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v6.0.2
-        if: env.USE_CODEQL == 'true'
         with:
           submodules: true
 
       - name: Run composite CodeQL job for '${{matrix.language}}' language
         uses: ./.github/actions/codeql
-        if: env.USE_CODEQL == 'true'
         with:
           language: ${{matrix.language}}
 
@@ -362,7 +386,7 @@ jobs:
   clang-tidy-clazy:
     name: Analyze (clang and clazy)
     runs-on: ubuntu-latest
-    if: ${{ vars.USE_CODEQL == 'true' && vars.USE_CODEQL && false || false }}
+    if: fromJSON(vars.USE_CODEQL || 'false') && false
 
     permissions:
       contents: read
